<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Vn.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="YarnSpinner.Compiler" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Vn.Core.Tests" />
  </ItemGroup>
</Project>